name: Deploy to Firebase Hosting Preview on Pull Request

"on":
   pull_request:
      types: [opened, synchronize, reopened]

permissions:
   checks: write
   contents: read
   pull-requests: write

jobs:
   build_and_preview:
      if: github.event_name == 'pull_request' && !contains(github.event.pull_request.title, 'bump')
      runs-on: ubuntu-latest

      strategy:
         matrix:
            node-version: [22.x]

      steps:
         - uses: actions/checkout@v4

         - name: Using Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v4.4.0
           with:
              node-version: ${{ matrix.node-version }}

         - name: Install pnpm
           uses: pnpm/action-setup@v4.1.0
           with:
              version: latest

         - name: Install dependencies
           run: pnpm install

         - name: Build project
           run: pnpm build

         - name: Deploy to Firebase Hosting Preview
           uses: FirebaseExtended/action-hosting-deploy@v0.9.0
           with:
              repoToken: ${{ secrets.GITHUB_TOKEN }}
              firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CODEPEN_CONCEPT }}
              channelId: "preview"
              expires: 5h
              projectId: codepen-concept
           env:
              FIREBASE_CLI_PREVIEWS: hostingchannels
              FIREBASE_CLI_EXPERIMENTS: webframeworks
