name: Lighthouse Performance Badges

"on":
   push:
      branches: [main]

jobs:
   lighthouseci:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         - name: Install Node.js
           uses: actions/setup-node@v4
           with:
              node-version: lts/*

         - name: Install pnpm
           uses: pnpm/action-setup@v4
           with:
              version: latest

         - uses: browser-actions/setup-chrome@v1
         - run: chrome --version

         - name: Generate Badges
           run: pnpx lighthouse-badges -u https://codepen-concept.web.app/ -o ./assets

         - name: Commit changes
           uses: EndBug/add-and-commit@v9
           with:
              add: "assets"
              author_name: github-actions[bot]
              author_email: github-actions[bot]@users.noreply.github.com
              message: "ci: update lighthouse peformance badges"
              push: true
